#:schema node_modules/wrangler/config-schema.json
name = "hartzell-hr-center"
main = "workers/index.ts"
compatibility_date = "2025-10-03"
compatibility_flags = ["nodejs_compat"]

# Account details
account_id = "b68132a02e46f8cc02bcf9c5745a72b9"

# D1 Database (Sessions, Audit Logs, Cache)
[[d1_databases]]
binding = "DB"
database_name = "hartzell_hr"
database_id = "a9a002e6-d7fb-4067-a2b2-212bf295ef28"

# KV Namespace (Redis-like caching for rate limiting & employee data cache)
[[kv_namespaces]]
binding = "CACHE"
id = "ae6971a1e8f746d4a39687a325f5dd2b"

# R2 Storage (Optional - for document storage if needed later)
# [[r2_buckets]]
# binding = "DOCUMENTS"
# bucket_name = "hartzell-documents"

# Environment Variables (non-secret)
[vars]
BITRIX24_ENTITY_TYPE_ID = "1054"
OPENSIGN_ENV = "sandbox"
SESSION_MAX_AGE = "28800"  # 8 hours in seconds
RATE_LIMIT_MAX_ATTEMPTS = "5"
RATE_LIMIT_WINDOW = "900"  # 15 minutes in seconds

# Routes - Map Workers to your domain
[[routes]]
pattern = "hartzell.work/api/*"
zone_name = "hartzell.work"

[[routes]]
pattern = "hartzell.work/*"
zone_name = "hartzell.work"

# Production environment
[env.production]
name = "hartzell-hr-center-production"
routes = [
  { pattern = "hartzell.work/*", zone_name = "hartzell.work" }
]

[env.production.vars]
OPENSIGN_ENV = "production"

# Staging environment
[env.staging]
name = "hartzell-hr-center-staging"
routes = [
  { pattern = "staging.hartzell.work/*", zone_name = "hartzell.work" }
]

# Development
[env.development]
name = "hartzell-hr-center-dev"

# Observability
[observability]
enabled = true
