#:schema node_modules/wrangler/config-schema.json
name = "hartzell-hr-center-production"
main = "workers/index.ts"
compatibility_date = "2025-10-03"
compatibility_flags = ["nodejs_compat"]

# Account details
account_id = "b68132a02e46f8cc02bcf9c5745a72b9"

# Routes - Production custom domain
routes = [
  { pattern = "hartzell.work/api/*", zone_name = "hartzell.work" }
]

# Environment Variables (non-secret)
[vars]
BITRIX24_ENTITY_TYPE_ID = "1054"
OPENSIGN_ENV = "sandbox"
SESSION_MAX_AGE = "28800"  # 8 hours in seconds
RATE_LIMIT_MAX_ATTEMPTS = "5"
RATE_LIMIT_WINDOW = "900"  # 15 minutes in seconds

# D1 Database (Production)
[[d1_databases]]
binding = "DB"
database_name = "hartzell_hr_prod"
database_id = "9926c3a9-c6e1-428f-8c36-fdb001c326fd"

# KV Namespace (Production)
[[kv_namespaces]]
binding = "CACHE"
id = "54f7714316b14265a8224c255d9a7f80"

# R2 Storage (Production)
[[r2_buckets]]
binding = "ASSETS"
bucket_name = "hartzell-assets-prod"

[[r2_buckets]]
binding = "DOCUMENTS"
bucket_name = "hartzell-hr-templates-prod"

# Observability
[observability]
enabled = true
