#:schema node_modules/wrangler/config-schema.json
name = "hartzell-hr-center-production"
main = "workers/index.ts"
compatibility_date = "2025-10-03"
compatibility_flags = ["nodejs_compat"]

# Account details
account_id = "b68132a02e46f8cc02bcf9c5745a72b9"

# Routes - Production custom domain
routes = [
  { pattern = "hartzell.work/api/*", zone_name = "hartzell.work" }
]

# Environment Variables (non-secret)
[vars]
BITRIX24_ENTITY_TYPE_ID = "1054"
SESSION_MAX_AGE = "28800"  # 8 hours in seconds
RATE_LIMIT_MAX_ATTEMPTS = "5"
RATE_LIMIT_WINDOW = "900"  # 15 minutes in seconds

# Secrets (set via: wrangler secret put SECRET_NAME)
# - SESSION_SECRET
# - BITRIX24_WEBHOOK_URL
# - OPENSIGN_API_KEY
# - RESEND_API_KEY (for email service)

# D1 Database (Production)
[[d1_databases]]
binding = "DB"
database_name = "hartzell_hr_prod"
database_id = "9926c3a9-c6e1-428f-8c36-fdb001c326fd"

# KV Namespace (Production)
[[kv_namespaces]]
binding = "CACHE"
id = "54f7714316b14265a8224c255d9a7f80"

# R2 Storage (Production)
[[r2_buckets]]
binding = "ASSETS"
bucket_name = "hartzell-assets-prod"

[[r2_buckets]]
binding = "DOCUMENTS"
bucket_name = "hartzell-hr-templates-prod"

# Cron Triggers (scheduled tasks)
# Daily at 9:00 AM Eastern Time (year-round) - email reminders
# Two triggers to handle EDT (UTC-4) and EST (UTC-5)
# - 13:00 UTC = 9:00 AM EDT (March-November)
# - 14:00 UTC = 9:00 AM EST (November-March)
# Handler includes guard logic to prevent duplicate execution
#
# REMOVED: Every-minute polling (was causing 56,000 KV writes/day)
# Stage change automation can be triggered via Bitrix24 webhooks instead
[triggers]
crons = ["0 13 * * *", "0 14 * * *"]

# Observability
[observability]
enabled = true
