name: Deploy Preview & Production

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          npm run build
        env:
          NEXT_PUBLIC_CLOUDFLARE_TURNSTILE_SITE_KEY: ${{ secrets.NEXT_PUBLIC_CLOUDFLARE_TURNSTILE_SITE_KEY }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}

      - name: Test responsive classes exist
        run: |
          echo "🔍 Verifying responsive grid classes in build..."

          # Check for md:grid-cols classes in all JS bundles
          MD_GRID_COUNT=$(find out/_next/static/chunks -name "*.js" -type f -exec grep -l "md:grid-cols" {} \; | wc -l)

          if [ "$MD_GRID_COUNT" -eq 0 ]; then
            echo "❌ ERROR: No md:grid-cols classes found in JavaScript bundles!"
            echo "This means mobile responsive design is MISSING."
            exit 1
          fi

          echo "✅ Found md:grid-cols classes in $MD_GRID_COUNT file(s)"

          # Check specific page bundle
          PAGE_BUNDLE=$(find out/_next/static/chunks/app/admin/employees/detail -name "page-*.js" 2>/dev/null | head -1)
          if [ -n "$PAGE_BUNDLE" ]; then
            if grep -q "md:grid-cols-2" "$PAGE_BUNDLE"; then
              echo "✅ Admin employee detail page has correct responsive classes"
            else
              echo "❌ ERROR: Admin employee detail page is missing md:grid-cols-2!"
              exit 1
            fi
          fi

          # Check CSS file
          CSS_FILE=$(find out/_next/static/css -name "*.css" 2>/dev/null | head -1)
          if [ -n "$CSS_FILE" ]; then
            if grep -q "md\\:grid-cols-2" "$CSS_FILE"; then
              echo "✅ CSS file contains md:grid-cols-2 classes"
            else
              echo "❌ ERROR: CSS file is missing md:grid-cols-2!"
              exit 1
            fi
          fi

          echo ""
          echo "🎉 All responsive design checks PASSED!"

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: hartzell-hr-frontend
          directory: out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}

      - name: Post-deployment verification
        if: github.ref == 'refs/heads/main'
        run: |
          echo "⏳ Waiting 30 seconds for deployment to propagate..."
          sleep 30

          echo "🔍 Verifying production deployment..."

          # Get the latest deployment URL
          PROD_URL="https://app.hartzell.work"

          # Check if the deployed JavaScript has responsive classes
          DEPLOYED_JS=$(curl -s "$PROD_URL/_next/static/chunks/app/admin/employees/detail/page-94ba048cdd21eb76.js" || echo "")

          if echo "$DEPLOYED_JS" | grep -q "md:grid-cols-2"; then
            echo "✅ Production deployment verified - responsive classes are live!"
          else
            echo "⚠️  WARNING: Production may still be serving old cached version"
            echo "This is normal if Cloudflare cache hasn't cleared yet"
          fi
